### ISSUE TITLE
unresolved import `windows::Win32::Foundation::PWSTR`

### ISSUE THREAD

**Issue by Aveline67** [l1npengtul/nokhwa#48]
```
   Compiling nokhwa-bindings-windows v0.3.4 (https://github.com/l1npengtul/nokhwa?branch=senpai#41abb00f)
error[E0432]: unresolved import `windows::Win32::Foundation::PWSTR`
   --> C:\Users\avlin\.cargo\git\checkouts\nokhwa-66b597f0abb1b795\41abb00\nokhwa-bindings-windows\src\lib.rs:382:13
    |
382 |             Foundation::PWSTR,
    |             ^^^^^^^^^^^^^^^^^ no `PWSTR` in `Windows::Win32::Foundation`
error: could not compile `nokhwa-bindings-windows` due to previous error
```

**Comment by l1npengtul** [comment]
It is being worked on.

**Comment by Aveline67** [comment]
How could i help ?

**Comment by l1npengtul** [comment]
Im working on it, 0.10 should be ready for  release next week or so
